In [1]:
from helper_functions.tourney_sim import simulate_tournament

WARNING:tensorflow:From C:\Users\mdona\AppData\Roaming\Python\Python39\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From C:\Users\mdona\AppData\Roaming\Python\Python39\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

WARNING:tensorflow:From C:\Users\mdona\AppData\Roaming\Python\Python39\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [25]:
import os
import numpy as np
import pickle
from tqdm import tqdm
import pandas as pd

In [4]:
x

'nn1.pickle'

In [5]:
all_models = []
for x in os.listdir('models'):
    with open('models/{}'.format(x), 'rb') as file:
        y=pickle.load(file)
    all_models.append(y)

In [9]:
all_results_repeat = [1]

In [8]:
all_results_dict = dict()
unique_values=1
all_results_dict[unique_values]=current_result

In [97]:
%%capture
for i in tqdm(range(1000)):
    current_result = simulate_tournament(strategy='nn', reps=1, auto=True, model=np.random.choice(all_models))
    if current_result in all_results_dict.values():
        all_results_repeat.append(list(all_results_dict.values()).index(current_result) + 1)
    else:
        unique_values+=1
        all_results_dict[unique_values]=current_result
        all_results_repeat.append(unique_values)

KeyboardInterrupt:

In [98]:
unique_values

1558

In [99]:
len(all_results_repeat)

1558

In [100]:
egg = []

In [101]:
for v in all_results_dict.values():
    egg.append(v[-1])

In [102]:
pd.Series(egg).value_counts()

UConn             413
North Carolina    131
BYU                77
Auburn             76
Purdue             70
                 ...
Kansas              2
Grambling           2
South Carolina      1
Long Beach St.      1
TCU                 1
Name: count, Length: 61, dtype: int64

In [103]:
with open('brackets/1000_sim_dict.pickle','wb') as handle:
    pickle.dump(all_results_dict, handle)

In [87]:
wins_list = []
for val in all_results_dict.values():
    wins_list.append(val[:32])

In [88]:
wframe=pd.DataFrame(wins_list)

In [90]:
for c in wframe.columns:
    col=wframe[c]
    vc=col.value_counts()
    print('Winner: {}. Pct: {}%'.format(vc.index[0], np.round(100*(vc.iloc[0]/len(all_results_repeat)), 2)))

Winner: UConn. Pct: 84.94%
Winner: Fla. Atlantic. Pct: 82.21%
Winner: San Diego St.. Pct: 82.73%
Winner: Auburn. Pct: 80.39%
Winner: BYU. Pct: 71.17%
Winner: Illinois. Pct: 63.77%
Winner: Washington St.. Pct: 67.53%
Winner: Iowa St.. Pct: 83.38%
Winner: North Carolina. Pct: 87.01%
Winner: Michigan St.. Pct: 53.25%
Winner: Saint Mary's (CA). Pct: 71.43%
Winner: Alabama. Pct: 50.65%
Winner: Clemson. Pct: 75.32%
Winner: Baylor. Pct: 70.78%
Winner: Dayton. Pct: 66.49%
Winner: Arizona. Pct: 83.9%
Winner: Houston. Pct: 55.84%
Winner: Nebraska. Pct: 60.39%
Winner: James Madison. Pct: 51.56%
Winner: Duke. Pct: 69.74%
Winner: Texas Tech. Pct: 77.27%
Winner: Kentucky. Pct: 70.0%
Winner: Boise St.. Pct: 63.25%
Winner: Marquette. Pct: 82.21%
Winner: Purdue. Pct: 91.17%
Winner: Utah St.. Pct: 73.38%
Winner: Gonzaga. Pct: 60.91%
Winner: Kansas. Pct: 64.03%
Winner: South Carolina. Pct: 61.82%
Winner: Creighton. Pct: 83.77%
Winner: Texas. Pct: 78.18%
Winner: Tennessee. Pct: 71.3%

In [79]:
wframe

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,Stetson,Fla. Atlantic,San Diego St.,Auburn,Duquesne,Illinois,Washington St.,Iowa St.,North Carolina,Mississippi St.,...,Florida,Marquette,Grambling,Utah St.,Gonzaga,Kansas,South Carolina,Creighton,Texas,Tennessee
1,UConn,Fla. Atlantic,San Diego St.,Auburn,Duquesne,Illinois,Washington St.,Iowa St.,North Carolina,Michigan St.,...,Boise St.,Marquette,Purdue,Utah St.,McNeese,Samford,Oregon,Creighton,Texas,Saint Peter's
2,UConn,Fla. Atlantic,San Diego St.,Yale,BYU,Morehead St.,Washington St.,Iowa St.,North Carolina,Michigan St.,...,Florida,Marquette,Purdue,Utah St.,Gonzaga,Samford,South Carolina,Akron,Texas,Tennessee
3,UConn,Fla. Atlantic,San Diego St.,Auburn,BYU,Illinois,Washington St.,Iowa St.,North Carolina,Michigan St.,...,Boise St.,Marquette,Purdue,Utah St.,McNeese,Kansas,South Carolina,Akron,Texas,Tennessee
4,UConn,Fla. Atlantic,UAB,Auburn,BYU,Illinois,Washington St.,Iowa St.,North Carolina,Mississippi St.,...,Boise St.,Marquette,Purdue,TCU,McNeese,Samford,South Carolina,Creighton,Texas,Tennessee
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
506,UConn,Fla. Atlantic,UAB,Auburn,Duquesne,Illinois,Washington St.,Iowa St.,North Carolina,Michigan St.,...,Florida,Marquette,Purdue,Utah St.,McNeese,Kansas,Oregon,Creighton,Virginia,Saint Peter's
507,UConn,Fla. Atlantic,San Diego St.,Auburn,BYU,Illinois,Drake,Iowa St.,Howard,Michigan St.,...,Florida,Marquette,Purdue,TCU,Gonzaga,Samford,South Carolina,Creighton,Texas,Saint Peter's
508,Stetson,Fla. Atlantic,San Diego St.,Auburn,BYU,Morehead St.,Washington St.,Iowa St.,North Carolina,Mississippi St.,...,Boise St.,Marquette,Purdue,Utah St.,McNeese,Kansas,South Carolina,Creighton,Virginia,Tennessee
509,UConn,Fla. Atlantic,San Diego St.,Yale,BYU,Morehead St.,Drake,Iowa St.,North Carolina,Michigan St.,...,Boise St.,Marquette,Purdue,Utah St.,McNeese,Kansas,Oregon,Creighton,Texas,Tennessee
510,UConn,Fla. Atlantic,San Diego St.,Auburn,BYU,Illinois,Washington St.,Iowa St.,North Carolina,Mississippi St.,...,Boise St.,Marquette,Purdue,Utah St.,McNeese,Samford,South Carolina,Akron,Virginia,Saint Peter's

In [ ]:
(home_scores>away_scores)

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,True,True,True,True,False,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True,True,True
2,False,True,False,True,True,False,False,False,False,True,False,True,True
3,True,False,True,False,True,False,True,True,True,True,True,True,True
4,False,True,False,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,True,True,True,False,False,True,True,False,True,True,True,True,True
96,True,False,True,True,True,True,True,True,True,True,False,True,False
97,True,True,True,True,False,True,True,False,True,False,False,True,True
98,True,True,True,True,True,True,True,True,True,False,False,True,True
99,True,True,True,False,True,False,True,False,False,True,False,True,True

In [76]:
wframe[0].value_counts().iloc[0]
b

439